apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node
                operator: In
                values:
                - vishalsecond
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node
                operator: In
                values:
                - ram
          - weight: 50
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - vishalenv
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
